[package]
name = "rust-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Document", "Window", "HtmlElement", "console"] }

[lib]
crate-type = ["cdylib"]
